import { SensorData, DeviceNode, AlertNotification } from '../types';

export const sensors: SensorData[] = [
  {
    id: '1',
    name: 'Soil Moisture',
    value: 42,
    unit: '%',
    trend: 'down',
    change: 2.4,
    icon: 'Droplets',
    chartData: [
      { time: '08:00', value: 45 },
      { time: '10:00', value: 44 },
      { time: '12:00', value: 43 },
      { time: '14:00', value: 42 },
      { time: '16:00', value: 42 },
    ],
  },
  {
    id: '2',
    name: 'Air Temp',
    value: 24.8,
    unit: '°C',
    trend: 'up',
    change: 1.2,
    icon: 'Thermometer',
    chartData: [
      { time: '08:00', value: 20 },
      { time: '10:00', value: 22 },
      { time: '12:00', value: 25 },
      { time: '14:00', value: 26 },
      { time: '16:00', value: 24.8 },
    ],
  },
  {
    id: '3',
    name: 'Humidity',
    value: 65,
    unit: '%',
    trend: 'stable',
    change: 0.5,
    icon: 'Wind',
    chartData: [
      { time: '08:00', value: 64 },
      { time: '10:00', value: 65 },
      { time: '12:00', value: 66 },
      { time: '14:00', value: 65 },
      { time: '16:00', value: 65 },
    ],
  },
  {
    id: '4',
    name: 'Light Intensity',
    value: 850,
    unit: 'lux',
    trend: 'up',
    change: 50,
    icon: 'Sun',
    chartData: [
      { time: '08:00', value: 300 },
      { time: '10:00', value: 600 },
      { time: '12:00', value: 900 },
      { time: '14:00', value: 1000 },
      { time: '16:00', value: 850 },
    ],
  },
  {
    id: '5',
    name: 'pH Level',
    value: 6.4,
    unit: 'pH',
    trend: 'stable',
    change: 0.1,
    icon: 'FlaskConical',
    chartData: [
      { time: '08:00', value: 6.5 },
      { time: '10:00', value: 6.4 },
      { time: '12:00', value: 6.4 },
      { time: '14:00', value: 6.4 },
      { time: '16:00', value: 6.4 },
    ],
  },
  {
    id: '6',
    name: 'CO2 Level',
    value: 412,
    unit: 'ppm',
    trend: 'up',
    change: 4,
    icon: 'Activity',
    chartData: [
      { time: '08:00', value: 400 },
      { time: '10:00', value: 405 },
      { time: '12:00', value: 410 },
      { time: '14:00', value: 415 },
      { time: '16:00', value: 412 },
    ],
  },
];

export const devices: DeviceNode[] = [
  {
    id: 'esp-01',
    name: 'ESPNODE 1',
    type: 'ESP32 Controller',
    status: 'online',
    battery: 85,
    signal: 92,
    lastUpdated: '2 mins ago',
  },
  {
    id: 'esp-02',
    name: 'ESPNODE 2',
    type: 'LTE Node',
    status: 'online',
    battery: 42,
    signal: 65,
    lastUpdated: '5 mins ago',
  },
  {
    id: 'pump-01',
    name: 'Irrigation Pump',
    type: 'Relay Module',
    status: 'offline',
    battery: 100,
    signal: 0,
    lastUpdated: '1 hour ago',
  },
];

export const alerts: AlertNotification[] = [
  {
    id: 'a1',
    title: 'Low Soil Moisture',
    description: 'Soil moisture in Sector 7 dropped below 30%.',
    type: 'warning',
    timestamp: '10:45 AM',
  },
  {
    id: 'a2',
    title: 'Pump Disconnected',
    description: 'Irrigation Pump A is not responding to ping requests.',
    type: 'alert',
    timestamp: '09:12 AM',
  },
  {
    id: 'a3',
    title: 'Maintenance Due',
    description: 'Sensor Node North Greenhouse requires battery replacement.',
    type: 'info',
    timestamp: 'Yesterday',
  },
];
